global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  # =====================
  # PROMETHEUS SELF
  # =====================
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "prometheus:9090"

  # =====================
  # POSTGRES
  # =====================
  - job_name: "postgres"
    static_configs:
      - targets:
          - "postgres-exporter:9187"

  # =====================
  # REDIS (MASTER)
  # =====================
  - job_name: "redis"
    static_configs:
      - targets:
          - "redis-exporter:9121"

  # =====================
  # KAFKA
  # =====================
  - job_name: "kafka"
    static_configs:
      - targets:
          - "kafka-exporter:9308"

  # =====================
  # NODE / HOST METRICS
  # =====================
  - job_name: "node"
    static_configs:
      - targets:
          - "node-exporter:9100"